stages:

  data_split:
    cmd: python ./src/data/01_data_splitting.py
    deps:
    - ./data/raw_data/raw.csv
    - ./src/data/01_data_splitting.py
    outs:
    - ./data/processed_data/X_test.csv
    - ./data/processed_data/X_train.csv
    - ./data/processed_data/y_test.csv
    - ./data/processed_data/y_train.csv

  normalization:
    cmd: python ./src/data/02_data_normalization.py
    deps:
    - ./data/processed_data/X_test.csv
    - ./data/processed_data/X_train.csv
    outs:
    - ./data/processed_data/X_test_scaled.csv
    - ./data/processed_data/X_train_scaled.csv

  params_grid_def:
    cmd: python ./src/data/03_params_grid.py
    outs:
    - ./models/param_grid.pkl

  model_training:
    cmd: python ./src/data/04_model_training.py
    deps:
    - ./data/processed_data/X_test_scaled.csv
    - ./data/processed_data/X_train_scaled.csv
    - ./data/processed_data/y_test.csv
    - ./data/processed_data/y_train.csv
    outs:
    - ./models/cv_reg_model.pkl

  model_evaluation:
    cmd: python ./src/data/05_model_evaluation.py
    deps:
    - ./data/processed_data/X_test_scaled.csv
    - ./data/processed_data/X_train_scaled.csv
    - ./data/processed_data/y_test.csv
    - ./data/processed_data/y_train.csv
    outs:
    - ./data/processed_data/y_test_preds.csv
    - ./data/processed_data/y_train_preds.csv
    - ./metrics/metrics.json
